pages/Login/index.js, pages/Login/index.module.css, styles/global.css
set up login page and change global.css color from --primary to --orange
=> primary to orange + Login setup

container/JobCreatePost/index.js, pages/Feed/Jobs/JobCreatePost/index.js, pages/Feed/Jobs/JobCreatePost/index.module.css, pages/Test/index.js, pages/Test/index.module.css
=> create feature post job

pages/Profile/FeatureDropDown/index.js, pages/Profile/FeatureDropDown/index.module.css, pages/Profile/index.js, pages/Profile/index.module.css
Still have to be able to edit name and upload image
next task: create my projects, my discussions, my jobs, view saved items
=> finished profile landing page V1

pages/Profile/MyDiscussions/index.js, pages/Profile/MyJobs/index.js, pages/Profile/MyProjects/index.js, pages/Profile/MySavedItems/index.js, pages/Profile/index.js, pages/Profile/index.module.css
reuse code nextPageHandler function in profile landing page and create routes for subfolder of the profile page
=> minor fixes in profile landing page

pages/Projects/ProjectDetail/index.js, pages/Projects/index.js
let user click the project div then connect to project detail page
=> add feature project landing page

pages/Profile/MyDiscussions/index.js, pages/Profile/MyDiscussions/index.module.css
Still have to decide where to edit
=> complete discussion ui

components/CircleButton/index.js, container/SignInInput/index.js, firebase/config.js, firebase/index.js, package-lock.json, package.json
Setting up firebase in firebase folder
-> try signInWithEmailAndPassword: done
-> still have to handle invalid user
-> figure out how to make user stayed log in
-> do firebase for sign up
=> firebase setup

pages/Feed/Discussions/Comments/index.js, pages/ForgetPassword/index.js, pages/ForgetPassword/index.module.css, pages/Profile/index.module.css
Create forgot password page:
The user will enter and email. Then, Firebase will sent a link to reset a password via user email address
=> feature[forgotPassword]

container/Discussion/index.js, lib/api/post.js, pages/Feed/Discussions/index.js, pages/ForgetPassword/index.js
get discussion details from postman and render it in discussion page
=> Try calling api

container/Discussion/index.js, pages/Feed/Discussions/index.js
Add show more button in discussion page
to do: add show more in other pages(news)
=> feature[show more]

container/SignUpInput/index.js, lib/api/discussions.js, lib/api/news.js, pages/Feed/Discussions/index.js, pages/Feed/News/index.js
get data from api for news and discussions page:
to do:
get username and user avatar, job page
=> feature[callAPI:news&discussions]

container/JobPost/index.js, container/JobPost/index.module.css, lib/api/jobs.js, pages/Feed/Jobs/index.js
Finish calling get-all-jobs and connecting it with frontend
=> feature[getJobApi]

components/ActivityButtonWithNumber/index.js, components/CommentButton/index.js, components/CommentButton/index.module.css, components/FeedDropDown/index.js, components/LikeButton/index.js, components/LikeButton/index.module.css, container/Discussion/index.js, container/Discussion/index.module.css, lib/api/discussions.js, lib/api/news.js, package-lock.json, package.json, pages/Feed/Discussions/index.js, pages/Feed/News/index.js
new like button and comment
still have to do the update on liked and unlike
Co-authored-by: booncoder123 <booncoder123@users.noreply.github.com>
=> [feat]like-button

components/Layout/Feed/index.module.css, components/RectangularButton/index.module.css, container/JobDetail/index.js, container/JobDetail/index.module.css, container/JobPost/index.js, lib/api/jobs.js, lib/api/projects.js, pages/Feed/Jobs/JobDetails/index.js, pages/Feed/Jobs/JobDetails/index.module.css, pages/Feed/Jobs/index.js, pages/Projects/index.js
Co-authored-by: booncoder123 <booncoder123@users.noreply.github.com>
=> feat[display-alljobs-jobsDetails]

components/RectangularButton/index.js, container/ProjectPost/index.js, container/ProjectPost/index.module.css, lib/api/projects.js, pages/Profile/index.js, pages/Profile/index.module.css, pages/Projects/CreateProject/index.js, pages/Projects/index.js
finish get-alll-project
stilll have to fix project details page
=> feat[projectPageApi]

container/ProjectPost/index.js, container/ProjectPost/index.module.css, lib/api/projects.js, pages/Projects/ProjectDetail/index.js, pages/Projects/ProjectDetail/index.module.css, pages/Projects/index.js, pages/Projects/index.module.css
=> feat[connectAPItoProjectDetail]

container/SignUpInput/index.js, lib/api/user.js, pages/Profile/index.js
still have to display user photo
=> feat[display-username]

container/Discussion/index.js, container/Discussion/index.module.css, container/ProfileDiscussion/index.js, lib/api/profile.js, pages/Profile/MyDiscussions/index.js
delete discussion in profile/myDiscussion page
Co-authored-by: booncoder123 <booncoder123@users.noreply.github.com>
=> feat[delete-mydiscussion]

container/Discussion/index.js, lib/api/profile.js, pages/Profile/MyDiscussions/index.js, pages/Profile/MyNews/index.js
display news by uid and able to delete news
=> feat[profile-mynews]

container/ProfileJob/index.js, container/ProfileJob/index.module.css, lib/api/profile.js, pages/Profile/MyJobs/index.js
able to display job by uid and deleted it
=> feat[profile-display/deletejobs]

container/ProfileJob/index.module.css, container/ProfileProject/index.js, container/ProfileProject/index.module.css, lib/api/profile.js, pages/Profile/MyProjects/index.js
=> feat[display-myproject]

container/Feed/FeatureDropDown/index.js, pages/Feed/Discussions/Comments/index.js, pages/Feed/Discussions/Comments/index.module.css, pages/Profile/FeatureDropDown/index.js, pages/Projects/FeatureDropDown/index.js
=> fix drop down image and comment image
